YML import and Mosaic Revoke support (hot fix)
symbol/catbuffer-generators pull request #166
Opened 2021-11-08 17:13 UTC by fboucquez

fix: loading schemas from exported symbol.yml
fix: updated java and typescript generators to new schemas names
fix: update transactions helpers to use versions and types
fix: updated vector tests to new network types.
feat: symbol.yml includes revocable mosaic schemas
fix: Added mosaic revoke related vector tests.

Note, this PR doesn't go to the dev branch because the dev branch has typescript features for the new SDK, not for the old one. Examples are bigint support and constants

2021-11-09 17:49 UTC, Jaguar0625 commented
can you please split this into (at least) two reviews and separate out the hotfix into its own review?

2021-11-09 18:46 UTC, fboucquez commented
I'll split, but we would need both PRs, new schemas/yml import and the new revoke schemas + vector tests. I cannot just include the revoke schemas as they were coded into the new catbuffer schemas that use the new parsers with export/import.

2021-11-09 18:58 UTC, fboucquez commented
@Jaguar0625 , this pr just includes the schema and parser upgrades for java and typescript. Revoke schemas will be on the next pr

2021-11-10 23:25 UTC, Jaguar0625 requested changes

2021-11-10 23:25 UTC, Jaguar0625 commented on generators/java/JavaHelper.py
>          return '{0} == {1}'
aren't you missing `not in` ?

2021-11-10 23:25 UTC, Jaguar0625 commented on generators/java/gradle-wrapper.properties
> +distributionUrl=https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
why is this file needed now?

2021-11-10 23:25 UTC, Jaguar0625 commented on test/vector/transactions.yml
> +  payload: B20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000F6503F78FBF99544B906872DDB392F4BE707180D285E
what is reason for changes in this file ?

2021-11-11 09:46 UTC, fboucquez commented on generators/java/gradle-wrapper.properties
> +distributionUrl=https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
Removed, for some reason, intellij keeps trying to download and use gradle 7. We haven't upgraded this generator yet.

2021-11-11 09:47 UTC, fboucquez commented on generators/java/JavaHelper.py
>          return '{0} == {1}'
Added 'not in' support to java and typescript

2021-11-11 09:48 UTC, fboucquez commented on test/vector/transactions.yml
> +  payload: B20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000F6503F78FBF99544B906872DDB392F4BE707180D285E
The original vector tests used private networks. The new schemas removed them so the vector tests needed to be recreated. This is the same file you have in the dev branch gimre has updated (I did the same in another experimental branch).

https://github.com/symbol/catbuffer-generators/blob/dev/test/vector/transactions.yml

2021-11-11 09:52 UTC, fboucquez commented
Hi @gimre-xymcity , have you merged the dev branch? It invalidates my hot fix for the revokable mosaics. I can publish a hot fix from this branch before merging though...

2021-11-11 13:02 UTC, fboucquez commented
Hi @Jaguar0625 @gimre-xymcity 

Can I move out these 3 commits from the main branch into an experimental? 

![image](https://user-images.githubusercontent.com/5390558/141302529-dd11aaff-171b-4354-a59f-afa3033e81c0.png)

https://github.com/symbol/catbuffer-generators/commits/main

They were going to be used in the new TS SDK before the schema updates, YML export/import, and the decision to move the generators out of this project into each SDK.

2021-11-11 14:43 UTC, Jaguar0625 approved these changes

2021-11-11 16:25 UTC, merged